VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsSpaceObject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get CollisionRadius() As Long

End Property

Public Property Get X() As Long

End Property

Public Property Get Y() As Long

End Property

Public Property Get Destroyed() As Boolean

End Property

Public Property Let Destroyed(SetDestroyed As Boolean)

End Property
